global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "vpn-exporter"
    scrape_interval: 30s
    static_configs:
      - targets: ["vpn-exporter:9101"]

  - job_name: "sonarr"
    static_configs:
      - targets: ["exportarr-sonarr:9707"]

  - job_name: "radarr"
    static_configs:
      - targets: ["exportarr-radarr:9708"]

  - job_name: "prowlarr"
    static_configs:
      - targets: ["exportarr-prowlarr:9709"]

  - job_name: "sabnzbd"
    static_configs:
      - targets: ["exportarr-sabnzbd:9710"]

  - job_name: "tautulli"
    scrape_interval: 30s
    static_configs:
      - targets: ["tautulli-exporter:9711"]

  - job_name: "health-exporter"
    scrape_interval: 30s
    static_configs:
      - targets: ["health-exporter:9112"]
